server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: one
          uri: lb://first-service
          predicates:
            - Path=/one/**
        - id: two
          uri: lb://second-service
          predicates:
            - Path=/two/**
