server:
  port: 8082


spring:
  cloud:
    gateway:
      routes:
        - id : microservice1
          uri : http://localhost:8080/
          predicates:
            - Path=/one/**
        - id: microservice2
          uri : http://localhost:8081/
          predicates:
            - Path=/two/**


